version: "2"
services:
  wpdb:
    image: mariadb
    ports:
      - 8081:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  wp:
    image: wordpress
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8181:80
    links:
        - wpdb:mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
